### ISSUE TITLE
Improve the CarMap and Driver design

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#139]
- Add a IAV-banner at the top
- Color the track lines in light blue (B3).
- Color the "You have been hacked"-screen in pink (M3)

**Comment by iav-BjRo** [comment]
done, ready for review
![image](https://github.com/user-attachments/assets/c9f4e513-3930-4f7e-8c4a-d141d3a2d4b4)
![image](https://github.com/user-attachments/assets/5378f7f5-51b6-4f70-8a5d-9e551e1e9cb3)
