### ISSUE TITLE
Configuration of the QR code style and background color

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#160]
The background color in the QR code area of the carMap-UI should always be identical to the background color of the track area.
It should be configurable via the staffUI whether a positive or negative style of the QR codes should be used.

**Comment by iav-BjRo** [comment]
svg files of the qr codes are used now. since svg files can be manipulated using javascript the color of the qr code and its background can be individually configured in the staff ui
