### ISSUE TITLE
limit "offset_from_center"

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#17]
limit "offset_from_center" to the maximum actual track width.

**Comment by iav-BjRo** [comment]
to be checked if already implemented

**Comment by iav-BjRo** [comment]
tested with current development branch ([commit: d029c1e22b7da561b80f21df946583e6d123a403](https://github.com/iavofficial/IAV_Distortion/tree/d029c1e22b7da561b80f21df946583e6d123a403)):

After navigating to one of the outside lanes and pressing the lane change button towards the boarder multiple times, the first press on the lane change button towards the middle of the track caused a lane change towards this direction. Therefore this behaviour is already implemented.

**Comment by iav-BjRo** [comment]
reviewed with @iav-DaBi
