### ISSUE TITLE
support QR-code for new player

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#19]
As an observer, I want to be invited to drive on a virtual racetrack (via QR code scan), so that I can easily try out the controls with my smartphone and thus become a driver with a low barrier to entry.

These have to be two QR-codes
1. connect to WIFI Accesspoint
2. Link to DriverUI

In the first approach these will be static QR-codes that can be printed.

For example like in the students presentation:

![Image](https://github.com/iavofficial/IAV_Distortion/assets/166706444/48b547d5-d360-47aa-a432-da3c388620e0)

**Comment by iav-BjRo** [comment]
Example for QR-code generator: 
https://www.qrcode-generator.de/solutions/wifi-qr-code/

**Comment by iav-DaBi** [comment]
Access to Distortion Wifi:
https://qrdesigner.app/de?gad_source=5&gclid=EAIaIQobChMImvTJ3r26hwMVFGeRBR3eUA3-EAAYASAAEgKbQfD_BwE&step=1&version=2

Access to Driver UI:
https://qrdesigner.app/de?gad_source=5&gclid=EAIaIQobChMImvTJ3r26hwMVFGeRBR3eUA3-EAAYASAAEgKbQfD_BwE&step=1&version=2

**Comment by iav-BjRo** [comment]
ToDo's:
- save screenshots of qr codes in repository
- create new ticket for further clarification for usage of qr code generators (for prettier qr codes)
