### ISSUE TITLE
display real cars on virtual race track

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#20]
As a driver of a virtual vehicle, I want to be able to drive on the same track with other virtual and real vehicles, in order to experience a sense of competition (free game).

Ausbaustufe 1:
- [x] #85 
- [x] #86 

Ausbaustufe 2:
- [x] #88 

Ausbaustufe 3:
- [x] #89 
- [x] #90

**Comment by m-braunschweig** [comment]
Reviewed with @iav-DaBi and merged in 599e9475cf17579d65eea3e86871a984dd38ee80
