### ISSUE TITLE
automatically vehicle connection

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#22]
Vehicles that are taken from the charging station (or placed on the racetrack) should automatically connect to the system and placed in the vehicle queue.

**Comment by iav-BjRo** [comment]
function has been added in the FleetController, can be turned on and off in the config_file

**Comment by iav-BjRo** [comment]
add one more test to verify stop_auto_discover

**Comment by iav-BjRo** [comment]
done, test added, merged to development
