### ISSUE TITLE
Player removed from the game screen

### ISSUE THREAD

**Issue by iav-BjRo** [iavofficial/IAV_Distortion#34]
**Is your feature request related to a problem? Please describe.**
No matter because of which reason the player is removed from the game (time up, timeout, inactive) the player is redirected to a screen saying "Playing time is over".

**Describe the solution you'd like**
Player should be informed with a small info why he was removed from the game. Besides there should be an option to get back in the queue for playing.

**Comment by iav-DaBi** [comment]
reviewed with @iav-BjRo
