### ISSUE TITLE
Add more hacking effects on vehicleplayer

### ISSUE THREAD

**Issue by iav-BjRo** [iavofficial/IAV_Distortion#49]
As a supervisor, I want players to be made aware of hacking attacks through vehicle manipulations. These manipulations should be represented by sporadic double U-turns (O-Turn) and inverted user inputs.

Development Note:
The effects should be implemented in the vehicle object so that both the physicalCar and the virtualCar are affected.

Effect Description:
- Sporadic O-Turns
> - At the beginning of the O-Turn effect, it should be executed once.
> - Then sporadically after a random time, it will be executed repeatedly.

- Inverted User Input
>- Right is swapped with left and left is swapped with right.
>- U-turns are disabled.
>- Full throttle is stop and stop is full throttle."

ToDo:

1. Add for each effect on Object in DataModel/Effects/HackingEffects that inherits from HackedEffect
2. Implement hacking effect in start and end method
3. Add HackingEffects in VehicleEffectList Enum
4. Import new EffectObjects in to CyberSecurityManager
5. Add new scenarios in CyberSecurityManager._setscenarios()

**Comment by iav-DaBi** [comment]
moved from 2.0.0, because of priority on IAA topics
