### ISSUE TITLE
Create unique pictures for virtual vehicles.  

### ISSUE THREAD

**Issue by iav-DaBi** [iavofficial/IAV_Distortion#87]
Create unique pictures for virtual vehicles, that follow the iav style guide

https://styleguide.iavgroup.local/styleguides/einfuehrung/

**Comment by iav-BjRo** [comment]
As discussed with @iav-DaBi for the first attempt, only color variants (not compliant to the IAV style guide) have been created, to have a quick fix to show virtual cars on the track that are easily identifiable and clearly differentiable from the real cars.
An advanced option on how to display the virtual cars on the track has to be discussed with @Sandominion.

- color variants of virtual vehicle images have been created
- high resolution images have been compressed for usage in application
- short instruction on how to compress images have been added in the README in https://github.com/iavofficial/IAV_Distortion/tree/master/doc/Images_high_resolution
- images have been configured in the config file

**Comment by iav-BjRo** [comment]
reviewed with @iav-DaBi 



![Image](https://github.com/user-attachments/assets/3813b71e-fad0-4ef1-a832-293750771941)
